### ISSUE TITLE
Example of response to INVITE

### ISSUE THREAD

**Issue by mheadd** [kirm/sip.js#1]
I've been having a play with this module - very cool!  I've thrown together a quick registrar example using Redis - https://gist.github.com/906216

I was wondering if you could provide a quick example of how to use this module respond to an INVITE.  

In other words, if I have two clients registered, and one sends an INVITE for the other, I want to retrieve the registration info. from Redis and then format a response to the client that initiated the call (putting the SIP address for the called party in the "contact" header).

Just not sure how to format the response.  

Thanks!

**Comment by Syed-AliHamza** [comment]
@mheadd  @kirm  
Can you guys tell me the name of the tool that you are using two test it?
I also have written a registrar server. I want to receive real-time audio and I have used dgram to receive the audio packets. but i am unable to find a tool which will send the audio packets. please guide.

**Comment by Syed-AliHamza** [comment]
I'm using https://tryit.jssip.net/ to make user agents although it's not just for audio calls. @mheadd  using your code it throwing the below error.
![image](https://github.com/kirm/sip.js/assets/46610321/a087caeb-60f4-4257-b0cb-8fa1ea89a292)
