### ISSUE TITLE
sip.send does not handle address related parameters correctly

### ISSUE THREAD

**Issue by jaroszan** [kirm/sip.js#101]
I am trying to send INVITE request as follows:

    sip.send({
	    	method: METHOD_INVITE,
		    uri: "tel:0049200000002",
	    	headers: {
                to: {uri: "tel:0049200000002"},
                from: {uri: "tel:0049500022002", params: {tag: rstring()}},
                'call-id': rstring(),
                cseq: {method: METHOD_INVITE, seq: Math.floor(Math.random() * 1e5)},
                contact: [{uri: CONTACT_URI}],
                route: [{"uri": ROUTE_URI, "params": {}}, {"uri": NEXT_ROUTE_URI, "params": {}}]
            }, 

However request prepared by sip.js and send out to the network has uri replaced with ROUTE_URI, NEXT_ROUTE_URI moves into first position and original uri is appended to route header, ie:

    uri: ROUTE_URI
    ....
    route: [{"uri": NEXT_ROUTE_URI, "params": {}}, {"uri": tel:0049200000002, "params": {}}]

**Comment by kirm** [comment]
rfc3261 is a bit fuzzy about route sets with uri's lacking lr paramer. However in section considering in-dialog request it says:

   If the route set is not empty, and its first URI does not contain the
   lr parameter, the UAC MUST place the first URI from the route set
   into the Request-URI, stripping any parameters that are not allowed
   in a Request-URI.  The UAC MUST add a Route header field containing
   the remainder of the route set values in order, including all
   parameters.  The UAC MUST then place the remote target URI into the
   Route header field as the last value.

and it repeats the same logic in section concerning route processing in proxies.

So in sip.js, if your first route uri lacks 'lr' parameter it will replace request-uri and request uri will be appended as last route header.

**Comment by jaroszan** [comment]
Can you please advise how to properly set parameter without a value (eg. 'lr')?

**Comment by kirm** [comment]
you can set lr parameter value to null or undefined or empty string. Or just pass uri with lr paremeter as a string to route.

**Comment by jaroszan** [comment]
I have route defined as follows:

    route: [{"uri": ROUTE_URI, "params": {transport: "UDP", lr: null, mode: "mt"}}, {"uri": NEXT_ROUTE_URI, "params": {lr: null}}]

And still request uri is replaced with ROUTE_URI. When I look at network trace I can see that:
1. "transport" and "mode" parameters are missing in route header
2.  'lr' parameter is located  outside angle brackets: 

     <sip:10.10.10.10:5060>;lr

It looks that parameters should be located inside angle brackets (rfc 3261):

> If the URI is not enclosed in angle brackets, any semicolon-delimited parameters are header-parameters, not URI parameters.

**Comment by kirm** [comment]
That's because you added lr parameter to route header, not uri. To add it to uri you have to add it params object if your uri is parsed, or to the uri string if your uri is a string.

**Comment by jaroszan** [comment]
Thanks a lot for your help!
