### ISSUE TITLE
REGISTER&authorization bugs

### ISSUE THREAD

**Issue by ruokid** [kirm/sip.js#142]
![image](https://user-images.githubusercontent.com/22818757/82807369-334cd380-9eba-11ea-95d3-ac8a8665317c.png)

**Comment by scp404** [comment]
And digest.authenticateRequest always return false

**Comment by scp404** [comment]
> And digest.authenticateRequest always return false

![image](https://user-images.githubusercontent.com/22818757/83250489-c5b2e700-a1da-11ea-9870-dc72d4d78632.png)

this can solve the problem, but not good enough

**Comment by kirm** [comment]
Thanks, for pointing out the typo.
Regarding digest.authenticateRequest always returning false, you 'fix' effectively disables authentication. Can you show me the entire exchange including the challenge?

**Comment by ruokid** [comment]
> Regarding digest.authenticateRequest always returning false, you 'fix' effectively disables authentication. 

sorry, I made a mistake, there is no problem
