### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sip1325** [kirm/sip.js#66]
Hi,

I have started going through sip.js code and sample examples. My requirement is to create a basic SIP gateway + registrar. Registrar part is OK and working fine for me (using make_call.js & registrar given in examples). That way I got both A & B party registered. 

Now to move forward, I need to :-

1) Receive INVITE from A party 
2) Forward the INVITE to B party (after registry lookup)
3) Receive 200 OK from B party and forward it back to A party 
4) A party is using websocket & B party is using UDP

* TRYING towards A party will be generated by gateway itself (and incoming TRYING from B party will be consumed within gateway itself).

Would appreciate if you could provide some pointers OR sample code to achieve the forwarding mechanism.

Thanks

**Comment by kirm** [comment]
There is an example in examples/websocket-proxy.js. I think it should work in your case as it is. Have you tried it?

If there is any problems with the example please let me know.
