### ISSUE TITLE
In transport layer code sip response is not being retransmitted in case of missing ACK

### ISSUE THREAD

**Issue by sipjsdev** [kirm/sip.js#67]
I am using transport layer to start sip stack. It is not retransmitting response message in case of missing ACK.Is it possible to retransmit message in transport layer?

**Comment by kirm** [comment]
Transport layer (started by sip.makeTransport) does not retransmit anything, retransmitting is a transaction/application layer job. To start transaction layer you have to call sip.start or sip.create. And transaction layer only retransmit unsuccessful responses to INVITE until it gets ACK, application should retransmit 2xx responses itself (this how INVITE server transactions defined in RFC 3261).
