### ISSUE TITLE
sip resend cuts off audio from some vendor

### ISSUE THREAD

**Issue by Charles546** [kirm/sip.js#72]
When making a call to callcentric, first 183 response established early media, and both direction work fine. However, sip.js keeps resending an INVITE every half seconds, causing callcentric to cut off the audio.  The media stream still presents, but all is silent.

My suggestion is to stop the "resending" once a non-ACK response is received.

**Comment by kirm** [comment]
Actually sip.js should stop resend INVITE after first response. Could you show me message logs?

**Comment by Charles546** [comment]
Not able to reproduce anymore.
