### ISSUE TITLE
How do I send requests through proxy?

### ISSUE THREAD

**Issue by Charles546** [kirm/sip.js#74]
Ok, I know we can use sip.js to implement a proxy.  But, how do I send a request through another proxy (e.g. another sip.js proxy acting like a SBC)?

- Thanks

**Comment by kirm** [comment]
You add route header to your request.

```javascript
rq.headers.route = [{uri: 'sip:proxy@somewhere.net;lr'}];
```
don't forget `lr` parameter in uri or sip.js will mess up your request uri.

**Comment by kirm** [comment]
I assume issue is solved.
