### ISSUE TITLE
make register

### ISSUE THREAD

**Issue by nvteam** [kirm/sip.js#77]
I have made asterisk server and created some users 
what Iam trying to do is register method 
that is my code 

 var sip = require('sip');

    var to = 'asrisk user';
    var from = 'user';
    var ip = 'my astrisk ip';
    var port = 5060;
    var sourcePort = 5060;
    var sourceIp = 'some source ';
    var tcp = false;
    var rport = true;
    var callId = Math.floor(Math.random() * 1e6).toString();
    var seq = Math.floor(Math.random() * 1e5).toString();

    var sipClient = sip.create({
      port          : sourcePort,
      publicAddress : sourceIp,
      rport         : rport,
      tcp           : tcp,
      udp           : !tcp
    });

    var register = {
      method : 'REGISTER',
      uri : 'sip:' + to + '@' + ip + ':' + port,
      headers: {
        to : { uri : 'sip:' + to + '@' + ip + ':' + port },
        from : { uri: 'sip:' + from + '@' + sourceIp + ':' + sourcePort, params : { tag : callId } },
        'call-id': callId,
        cseq: { method : 'REGISTER', seq: seq },
        'content-type': 'application/sdp',
        contact : [ { uri: 'sip:' + from + '@' + sourceIp + ':' + sourcePort } ],
        'Max-Forwards': 70
      }
    };

    sipClient.send(register, function(ress) {
    
      sipClient.destroy();
      return res.json({
        result:ress
      })
    });
  }

But I Always get 503 response 
what is wrong with my code 
thanks

**Comment by kirm** [comment]
Maybe asterisk is confused by presence of content-type header in your registration request. REGISTER typically does not have content and content-type.

Or it maybe some asterisk configuration issue, try some other client with your server.

**Comment by nvteam** [comment]
thanks 
that is work
