### ISSUE TITLE
How can I know if no response arrived

### ISSUE THREAD

**Issue by nvteam** [kirm/sip.js#80]
hello kirm 

when i send request and got no response 
how can I know that to cancel request 

sipClient.send(sipHeader,function(msg){

})

thanks

**Comment by kirm** [comment]
You will receive 503 'service unavailable' response generated internally by transaction layer of sip.js.

**Comment by Wildsoft** [comment]
Should not it be 408 (request timeout)?

**Comment by kirm** [comment]
You're right it should be 408.
