### ISSUE TITLE
Example for sending messages from one UAC to another

### ISSUE THREAD

**Issue by PugMcThug** [kirm/sip.js#82]
Do you have an example for sending a text message from one SIP UAC to another via the SIP-Registrar? I gather that the relevant code would be in this block:

	if (trim(request.method) == 'MESSAGE') {
		console.log("Got MESSAGE") ;
		//Perform Voodoo
	}

Pug McThug

**Comment by kirm** [comment]
No i do not have such an example. But MESSAGE is pretty standard sip request there is nothing special to it.

It should be something like

```
sip.send({
	method: 'MESSAGE',
	uri: 'sip:someone@somethere.net',
	headers: {
		from: {uri: 'sip:user1@domain.com', params{tag: crypto.randomBytes(16).toString('hex')},
		to: 'sip:someone@somethere.net',
		'call-id': crypto.randomBytes(16).toString('hex'),
		'cseq': {method: 'MESSAGE', seq: 1},
		'content-type': 'text/plain'
	},
	content : 'some message'
}, function(rs) {
	console.log(rs);
});

```

On server you should receive it in sip.start callback and send 200 OK response

**Comment by PugMcThug** [comment]
Hi Kim,
thanks for the response and the tip, I'll try it out.

Pug McThug
