### ISSUE TITLE
How to run SIP proxy on a cluster

### ISSUE THREAD

**Issue by digttelecom** [kirm/sip.js#83]
How to run SIP proxy on a cluster (using module "cluster" )?

**Comment by kirm** [comment]
I do not have any direct experience with cluster module. But there is a lengthy discussion of using it in issue #23.

**Comment by kirm** [comment]
I think this simplest working example 

    var cluster = require('cluster');
    var numCPUs = require('os').cpus().length;
    var sip = require('sip');

    if (cluster.isMaster) {
  	  // Fork workers.
  	  for (var i = 0; i < numCPUs; i++) {
  		  worker = cluster.fork();
  	  }
  
  	  cluster.on('online', function (worker, code, signal) {
  		  console.log('worker ' + worker.process.pid + ' online');
  	  });
    } 
    else {
  	  var tcpTransport = sip.makeTransport({
  		  udp: false,
  		  tcp: true
  		  //logger: { recv: console.log, send: console.log} 
  	  }, onReceive);
      
  	  function onReceive(message, remote) {
  		  if (message.method) {
  			  tcpTransport.send(remote, sip.makeResponse(request, 486, 'Busy Here'));
  		  }
  	  }
    }
