### ISSUE TITLE
incorrect parsing of via header

### ISSUE THREAD

**Issue by jaroszan** [kirm/sip.js#86]
It seems that parsing of via header is not entirely correct. In the response the 'received' parameter is being appended to via header.

It is clearly seen both in wireshark traces and by printing incoming 'via' header with console.log(request.headers.via). 

For example I am sending an INVITE to sip.js client with via header, let's say 'x', and response to this request contains via header 'x;received:{source_address}'

**Comment by kirm** [comment]
That is actually intended behaviour. See rfc 3581.

**Comment by jaroszan** [comment]
Thanks for the tip, I wasn't aware of this one before.
