### ISSUE TITLE
net binding

### ISSUE THREAD

**Issue by 0bscur3** [kirm/sip.js#89]
When I try to use your library I get the following error:

node_modules/sip/sip.js:18
  var binding      = process.binding('net');
                             ^
Error: No such module: net
    at Error (native)
    at /node_modules/sip/sip.js:18:30
    at Object.<anonymous> (/node_modules/sip/sip.js:117:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/start.js:2:11)

I am running an Ubuntu 14.04

**Comment by kirm** [comment]
You are using very very old version of sip.js.

**Comment by 0bscur3** [comment]
Is the npm version older than the one in git?

**Comment by kirm** [comment]
No but the line your exception is thrown from - was removed years ago.

**Comment by blargman66** [comment]
I also had this problem today:
Fresh download of node.js for Windows.
npm init...
npm install sip
Write a basic app with require('sip')
Same issue as above

It appears the version (0.0.2-43) in https://registry.npmjs.org/ is broken.
I did a manual install of (0.0.2-42) and it was fine.

**Comment by 0bscur3** [comment]
@blargman66 thanks, it worked for me.

**Comment by kirm** [comment]
It seem if execute npm install sip, it installs first version of 0.0.2 instead of latest version. I republished it as 0.0.3 and it seems to resolve the problem

**Comment by blargman66** [comment]
I can confirm this is fixed
