### ISSUE TITLE
Message default via header

### ISSUE THREAD

**Issue by 0bscur3** [kirm/sip.js#90]
By default a via header is generated when I send a new message. Unfortunatley the via header contains the hostname of the sender instead of the ip address. This causes problems in my network. 

Therefore, I tried to set the via header manually, which results in 2 via headers. This is corresponding wireshark frame for the sended message:

```
REGISTER sip:xxxxxxx:7400 SIP/2.0
Via: SIP/2.0/UDP hostname:7400;branch=z9hG4bK551514;rport
Via: SIP/2.0/UDP 10.64.68.171:5060;branch=z9hG4bK82817
From: xxx <sip:xxx@10.64.68.171:7400>
To: xxx <sip:xxx@xxxxxx>
CSeq: 1 REGISTER
Contact:  <sip:xxx@10.64.68.171:7400>
Max-Forwards: 70
Expires: 240
Supported: 100rel,path
Content-Length: 0
Call-ID: 342406
```

**Comment by kirm** [comment]
From the api.markdown doc. 

sip.start(options, onRequest)

Starts SIP protocol.

options - an object optionally containing following properties.

publicAddress, hostname - address and hostname to be used within sip.js generated local uris and via headers. Sip.js will use options.publicAddress when it's defined, then fallback to options.hostname and the fallback to value returned by node.js os.hostname() API.

**Comment by 0bscur3** [comment]
Thanks for your help. Everything works now. Sorry for missing this in your doc!
