### ISSUE TITLE
sip.js:1332 rq is undefined

### ISSUE THREAD

**Issue by amykhajlyshyn** [kirm/sip.js#91]
when route lr parameter is absent I get exception here:
m.headers.route.push({uri: rq.uri});

probably m should be instead of rq. the same thing here:

if(typeof m.headers.route === 'string')
          rq.headers.route = parsers.route({s: m.headers.route, i:0});

Thanks,
Andrew

**Comment by kirm** [comment]
Thanks, i think i fixed it in commit 49888be

**Comment by amykhajlyshyn** [comment]
Thank you!
