### ISSUE TITLE
sip.start callback only executed once

### ISSUE THREAD

**Issue by 0bscur3** [kirm/sip.js#93]
When I try something like this and I get multiple requests only the first request is logged in console.

```javascript
sip.start({
	port: PORT,
	publicAddress: IP,
	udp: true,
	tcp: false
}, function(request, remote) {
	console.log("Got new Request:");
	console.log(request.headers);
});
```

**Comment by kirm** [comment]
Are you sure you're sending it requests with different transaction ids?

**Comment by 0bscur3** [comment]
The transaction ids are the same. Are only different ones progressed?

**Comment by kirm** [comment]
Yes, only request that created transaction will be delivered. All requests with same transaction id (in transaction lifetime) are assumed to be retransmits of original.

**Comment by 0bscur3** [comment]
Okay, thanks for explaining.
