### ISSUE TITLE
Is there simple way to get stream end/close events?

### ISSUE THREAD

**Issue by amykhajlyshyn** [kirm/sip.js#95]

**Comment by kirm** [comment]
I don't even know what a stream is. So no.

**Comment by amykhajlyshyn** [comment]
Hi!

Sorry, for missing details. I mean TCP/TLS stream. There is no access to underlying TCP/TLS stream if using sip.start / sip.create.

Andrew

**Comment by kirm** [comment]
Still no. Sip.js idea was to reduce appplication interface to sip messages, they are complex enough by themselves. But why do you need such low-level events?

**Comment by amykhajlyshyn** [comment]
I'm developing sip server and I need to know when client disconnects so I can remove registration context and stop forwarding requests to that client. Maybe you can suggest some better way for handling this. It would be very useful.

**Comment by kirm** [comment]
I don't think this is correct behaviour for sip registrar. In general sip clients are not required to maintain connection to registrar server. And even 'outbound' rfc does not require registrar to kill registration on flow death.

**Comment by amykhajlyshyn** [comment]
Ok, current behavior is 500 response when I try to forward request to disconnected client because I get connection error because sip.js tries to connect client who is behind NAT. Is it possible to do this in some other way?

**Comment by kirm** [comment]
Well it is correct response. And even clients behind NAT may not connect to your server directly but via edge proxy (in their nat router for example). And if client was removed gracefully it would have removed the registration. And in any case transport detects flow death by absence of keep-alive messages. And you can set expire timer for your registrations to be equal to keep-alive interval (30 seconds) recommended by 'outbound' rfc.

**Comment by amykhajlyshyn** [comment]
Oh, probably I got this. I implemented my own mechanism for registration and contacts mapping but I should use encodeFlowUri instead and I'll get desired 404 response which is built-in in sip.js when it cannot find mapping for contact.

**Comment by amykhajlyshyn** [comment]
Finally I found what I was looking for in RFC: http://tools.ietf.org/html/rfc5626#section-7 . It says:

If a proxy or registrar receives information from the network that
   indicates that no future messages will be delivered on a specific
   flow, then the proxy MUST invalidate all the bindings in the target
   set that use that flow (regardless of AOR).  Examples of this are a
   TCP socket closing or receiving a destination unreachable ICMP error
   on a UDP flow.  Similarly, if a proxy closes a file descriptor, it
   MUST invalidate all the bindings in the target set with flows that
   use that file descriptor.

Thus, I'll need to implement my own mechanism to catch TCP socket close event.

**Comment by kirm** [comment]
Ok, then you can call sip.makeTransport, cache returned object and pass it to sip.makeTransaction layer. Object returned from makeTransport has open method, which receives 2 arguments flowid and callback which will be called on flow death.

**Comment by amykhajlyshyn** [comment]
Wow, that's exactly what I need. Thank you!

**Comment by kirm** [comment]
Unfortunately it is exactly interface for disconnection events. It increases reference count on a flow and thus prevents server from closing inactive flows. And you need to call transportlayer.destroy on opened flows eventually.

You may use it for notifications on client initiated disconnect for now. I think i will have to implement some kind of actual events interface sometime in the future.

**Comment by amykhajlyshyn** [comment]
Yes, I understood. Thank you anyway.

**Comment by amykhajlyshyn** [comment]
I see that I need to copy paste sip.create method to implement what I need. I think I'll make my local fork to make things simpler :)
